### PR TITLE
Added unbound

### PR DESCRIPTION
**Pull request by Joly0**
Ok, so i am done and this does work. It might be smart to change the args for unbound in the dockerfile to variables aswell and give them as an argument when building the docker image. Also the cd in line 27 shozuld be a variable, but i left it as is for testing purposes without needing a ci/cd for now

### CODE REVIEW

**Comment by Joly0** [comment]
Solves https://github.com/devzwf/pihole-dot-doh/issues/11

**Comment by Joly0** [comment]
And another thing to note: Whenever the upstream pihole container decides to switch from bullseye to bookworm or anything else for their pihole/pihole:latest image, then the image for the first stage build needs to be updated aswell, otherwise openssl for unbound might not work. 

While testing i used bookworm for the first stage, while the second was still on bullseye and unbound complained, i changed the first on to match the second one and that worked. Might be smart to us the same image for both stages (so pihole/pihole:latest) but that made it take longer to build for me. Might not be a big issue for an automated build, but thats nothing i want to decide on my own :)

**Comment by Joly0** [comment]
Ye, should be ready to go

**Comment by devzwf** [comment]
Thanks 
i will review when i get back in the country this week-end.

**Comment by Joly0** [comment]
Just so you know, Unbound 1.19.3 is released, so the dockerfile would need to be updated

**Comment by devzwf** [comment]
I will be home tomorrow.
I will update to 1.19.3
But i was thinking of creating an other image with unbound instead of adding it to the image many are using .....
what do you think ?

**Comment by Joly0** [comment]
I mean, it shouldnt change anything for users who already use your containet, but if you feel safer like that, then sure

**Comment by devzwf** [comment]
I have build a dev image : devzwf/pihole-dot-doh:dev
please test it 
also can you add quick doc to use unbound instead ... if you cant i will
Thanks again

**Comment by Joly0** [comment]
I have just changed a little thing so the variable for the unbound version is used for the folder aswell, this should make a difference, but you could try to build a dev build again and i can check if that works.

Otherwise i will add some documentation later when i am at home

**Comment by Joly0** [comment]
Ok, i have added some documentation

**Comment by Joly0** [comment]
Hey @devzwf have you had time to look over it? Is the readme good like that?

**Comment by devzwf** [comment]
look at it now ,
will create a image so you can test as last mesure
then i will merge

**Comment by devzwf** [comment]
@Joly0 i create an image to test [2024.03.20dev](https://hub.docker.com/layers/devzwf/pihole-dot-doh/2024.03.20dev/images/sha256-f324858a2b8ef86da87a8e359f898fd87af5641b4f53084b035b225c65c20c60?context=repo)
i will be testing as well , iff all good i should be able to merge tomorrow
Thanks for all

**Comment by Joly0** [comment]
Works good for me so far

**Pull request merged**
