### PR TITLE
Create update-unbound.yml

### PR DESCRIPTION
**Pull request by Joly0**
Hey, this pr creates a github workflow, which runs once per day and checks, if a new version of unbound has been found. If it does, it creates a new pr which updates the dockerfile accordingly to reflect the new unbound release.

I have noted in my original pr for adding unbound, that this is still needed, but as i am not familiar with github actions, i cant do this. i have created this workflow file using chatgpt and i have tested it on my fork, and it seems to work there. I have noticed, that there is a new version of unbound (1.20.0), so there is a need to update unbound in this container aswel

### CODE REVIEW

**Comment by devzwf** [comment]
I think it is missing some condition,  i do not want it update the dockerfile every day unless i miss something .
the action should check first if the version is current or not before mod the Dockerfile .
Let me know if i miss something

**Comment by Joly0** [comment]
You are right, i havent thought about that.
I have updated the workflow file, so a pr only gets created, when a new unbound version has been found. I also added the option to run the workflow manually, that might be useful for testing maybe. I also merged the created pull request into my fork, so unbound should be on the latest version

**Comment by Joly0** [comment]
And found a bug, accidentally.used the sha1 hash, instead of sha256, so the docker build process would run correctly and error out. Havent noticed this while testing, but did now and fixed it

**Comment by Joly0** [comment]
Ok, so its ready to merge. Works on my fork

**Comment by devzwf** [comment]
I will review 
thanks

**Pull request merged**
